//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctors247
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class d_registration
    {
        [Required(ErrorMessage = "Please ennter your Username", AllowEmptyStrings = false)]
        public string username { get; set; }

        public int doctor_id { get; set; }
        
        [Required(ErrorMessage = "Please enter your firstname", AllowEmptyStrings = false)]
        public string first_name { get; set; }

        [Required(ErrorMessage = "Please ennter your lastname", AllowEmptyStrings = false)]
        public string last_name { get; set; }

        [Required(ErrorMessage = "Please ennter your email", AllowEmptyStrings = false)]
        public string email { get; set; }

        [Required(ErrorMessage = "Please ennter your password", AllowEmptyStrings = false)]
        public string pass { get; set; }


        [Required(ErrorMessage = "Please ennter your contact", AllowEmptyStrings = false)]
        public int contactNO { get; set; }


        [Required(ErrorMessage = "Please ennter your speciality", AllowEmptyStrings = false)]
        public string speciality { get; set; }


        [Required(ErrorMessage = "Please ennter your address", AllowEmptyStrings = false)]
        public string Addresss { get; set; }


        [Required(ErrorMessage = "Please ennter your designation")]
        public string designation { get; set; }

        [Required(ErrorMessage = "Please ennter your fees", AllowEmptyStrings = false)]
        public int Fees { get; set; }
    }
}
