//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctors247
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Doctors247EntitiesM : DbContext
    {
        public Doctors247EntitiesM()
            : base("name=Doctors247EntitiesM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<d_registration> d_registration { get; set; }
        public virtual DbSet<hospital> hospitals { get; set; }
    
        public virtual ObjectResult<GetHospital_Result> GetHospital()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHospital_Result>("GetHospital");
        }
    }
}
