//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctors247
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        public int UserId { get; set; }
        public string Date { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Imarge { get; set; }
        public string Role { get; set; }
        public string Details { get; set; }
        public string Salt { get; set; }
    }
}
