//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctors247
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Comments
    {
        public int CommentId { get; set; }
        public string Date { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public int PostId { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Image { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
    }
}
