//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctors247
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Posts
    {
        public int PostId { get; set; }
        public string Date { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string AuthorImage { get; set; }
        public string Image { get; set; }
        public string Categories { get; set; }
        public string Tags { get; set; }
        public string PostData { get; set; }
        public int Views { get; set; }
        public string Status { get; set; }
    }
}
